### ISSUE TITLE
Company Status - 'Closed-On'

### ISSUE THREAD

**Issue by wreid306** [kevbite/CompaniesHouse.NET#28]
See screenshot, had a search result bring back 'closed-on' as the company status which doesnt exist in
LiberisLabs.CompaniesHouse.Response.CompanyStatus

Can we have this added in please? 

![screenshot](https://cloud.githubusercontent.com/assets/10054139/18514549/e7bfa2a6-7a89-11e6-942c-a7c03881b11f.png)

![2016-09-14 14_52_06-khinnect crm](https://cloud.githubusercontent.com/assets/10054139/18514798/de1daee0-7a8a-11e6-9a22-b6092e8ff08e.png)

**Comment by kevbite** [comment]
`closed-on` isn't even part of their api documentation - https://github.com/companieshouse/api-enumerations/blob/master/constants.yml#L101

Not sure what the difference is between `closed` and `closed-on`, unless it means its due to be closed in a future date?

Adding the extra enumeration shouldn't be an issue, I'll try get this sorted tomorrow.

**Comment by kevbite** [comment]
This is now fixed in version 1.4.7

**Comment by wreid306** [comment]
Many Thanks!
