### ISSUE TITLE
Would it be possible to extend the Officer class so that I can get the nationality

### ISSUE THREAD

**Issue by JulianGuppy** [kevbite/CompaniesHouse.NET#84]
Proposed:-
In Officer.cs

        [JsonProperty(PropertyName = "nationality")]
        public string Nationality { get; set; }

I need to know the nationality of a director as part of the verification KYC/AML on my project so this would be very handy.

Regards Julian

**Comment by kevbite** [comment]
Hello,
Sounds perfectly fine, It looks like they've added a bunch of new properties to the Officers response since last time I had a look -https://developer.companieshouse.gov.uk/api/docs/company/company_number/officers/officerList-resource.html

Also, I've noticed that they don't return a officers overview anymore on the companies profile response - https://developer.companieshouse.gov.uk/api/docs/company/company_number/companyProfile-resource.html

I'd like to get these tired up too as they're quite related. Thanks for submitting the PR #85 I'll take a look tonight after I've finished work and at least get that bit of functionality merged it before tomorrow.

Cheers

**Comment by kevbite** [comment]
Changes have been included and will be in release [6.0.0](https://www.nuget.org/packages/CompaniesHouse/6.0.0)
